# Generated by Django 5.0.3 on 2024-05-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('assunto', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name_plural': 'Imagens'},
        ),
    ]
